### ISSUE TITLE
R201 value query

### ISSUE THREAD

**Issue by wile1411** [quezadaminter/GrblJogCtrlSchematic#2]
Is R201 in the button matrix supposed to be 1K and not 10k?
I ask as setting it to 10k would make the pin float when the button is pushed wouldn't it?

**Comment by wile1411** [comment]
I'm having a crack at replicating this as it seemed a great project for the holidays. Teensy implementations worked well.
I've make my own button board. Wiring up the selectors after this.

**Comment by wile1411** [comment]
By the way, thanks so much for a fantastically documented project. The man-in-the-middle is a great solution while keeping all the flexibility and I'm very much enjoying building this.

**Comment by quezadaminter** [comment]
Hi @wile1411,
I'm glad you are finding this project worth your time :). I am out of town and I cannot check the board first hand. I'll see if I can find some other pictures on my phone that may provide a clue on the value of the R201. If I can't find it right away I'll report back as soon as I get back home. I'll also take a look again at the schematics to see if I can work it out from there. Good luck!

**Comment by quezadaminter** [comment]
Just looking at the schematic, I think you are right. It definitely makes sense to make R201 a 1K resistor instead of 10K. I will double check the hardware when I get home but it does make sense. I'll amend the schematic once I get a chance. Thank you for catching this!

**Comment by quezadaminter** [comment]
I updated the schematic to show the change on R201 from 10K to 1K. Thank you for picking this out!
