### ISSUE TITLE
Has this been tested yet?

### ISSUE THREAD

**Issue by GeorgeIoak** [quezadaminter/GrblJogCtrlSchematic#3]
Thanks for sharing your design. I'm looking at a similar project that will use this 3.5" LCD panel from Buy Display and I wanted to know if you've built this and confirmed that the display breakout board worked.

**Comment by quezadaminter** [comment]
This schematic is part of a project. I am not sure when you ask if it has been tested, which part of the project you are referring to. This is what the screen looks like where I am using the schematic in this repository:

https://github.com/quezadaminter/GrblJogCtrl/blob/master/1.gif

**Comment by GeorgeIoak** [comment]
Sorry, I was referring to the LCD board uploaded to OSH Park? Is that version built and working? Looks like it is but I wasn't sure if the design files posted here matched what was shown in the video

**Comment by quezadaminter** [comment]
Got it. The oshpark board does work, it has been tested. You are also correct that it is not the same as the one in the videos which is an earlier version. The current version moves some of the hardware onto the board so you don't have to do what I did to the one on the video and hack the components onto it.

Good luck with your project, happy to answer any other questions. If you find this one answered please remember to close the issue :).

**Comment by GeorgeIoak** [comment]
Perfect, just wanted to make sure since sometimes repos and hardware can be out of sink and I was trying to not make the "same mistake"!
